### ISSUE TITLE
/task/run couldn't be found

### ISSUE THREAD

**Issue by napsta32** [UCL-INGI/INGInious-problems-demo#1]
When testing new problem with default container and pythia1compat, with any submission I receive this error.

**Comment by anthonygego** [comment]
This is normal. You should either:

- Write a run script for usage with Docker containers that will fetch user input using the INGInious API. Have a look at http://inginious.readthedocs.io/en/latest/teacher_doc/run_file.html
- Make the MCQ agent support/make a new agent that supports direct Python grading of your problem type.
